person:
    last-name: world
    age: 18
    boss: false
    birth: 2005/12/12
    maps: {k1: v1,k2: 12}
    lists:
        - lisi
        - zhaoliu
    dog:
        name: doggy
        age: 3


personV:
    last-name: "Hello world"
    age: 18
    boss: false
    birth: 2005/12/12
    maps: {k1: v1,k2: 12}
    lists:
        - lisi
        - zhaoliu
    dog:
        name: doggy
        age: 3

server:
    port: 8081
spring:
    profiles:
        active: dev
---
server:
    port: 8084
spring:
    config:
        activate:
            on-profile: test
---
server:
    port: 8085
spring:
    config:
        activate:
            on-profile: uat